# auto: true

markdown: kramdown
highlighter: rouge
paginate: 8
permalink: /:title
encoding: UTF-8
gems: [jekyll-paginate]

title: 邓尚律
url: http://dengshanglv.github.io
feed: /atom.xml
author_info: <a href="http://litaotao.github.io/">dengshanglv</a>

myblog:
  gavatar: 
  gpname: dengshanglv
  linkedin: https://www.linkedin.com/in/尚律-邓-145255124?
  github: https://github.com/dengshanglv
  email: mailto:dengshanglv@foxmail.com
  coverimgs: ['images/3.jpg']
  postbgimg: ['images/1.jpg']

categories: [at_uqer, days_and_nights]
