# auto: true

markdown: kramdown
highlighter: rouge
paginate: 8
permalink: /:title
encoding: UTF-8
gems: [jekyll-paginate]

title: 邓尚律
url: http://dengshanglv.github.io
feed: /atom.xml
author_info: <a href="http://litaotao.github.io/">dengshanglv</a>

myblog:
  gavatar: 
  gpname: dengshanglv
  linkedin: http://www.linkedin.com/in/邓尚律
  github: https://github.com/dengshanglv
  email: mailto:dengshanglv@foxmail.com
  coverimgs: []
  postbgimg: []

categories: [python, books]
